services:
  sftp:
    platform: linux/amd64
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data:/home/foo/upload
    environment:
      SFTP_USERS: "foo:pass:1001:100:upload"